GET http://localhost:5021/

###
POST http://localhost:5021/browsejobs
Content-Type: application/json

{

"companyname":" Google",
"contactnumber":"7644532285",
"email":"google@gmail.com",
"description":"once upon a time their lived a god.",
"state":"Telagana",
"country":"India",
"salary":"15-20 LPA",
"role":"Web Designer",
"experience":"5 years",
"no_of_applications":"30"

}
###
GET http://localhost:5021/allusers

