POST http://localhost:5016/appliedjobs
Content-Type: application/json

{

"companyname":"Tcs solutions",
"contactnumber":"9867765645",
"email":"tcs@gmail.com",
"description":"Foundational endpoint security controls across all Windows, macOS and Linux endpoints. Boost your organization's security with 7 best practices to secure your workstations. Remove Local Admin Foundational endpoint security controls across all Windows, macOS and Linux endpoints Foundational endpoint security controls across all Windows, macOS and Linux endpoints.",
"state":"Telagana",
"country":"India",
"salary":"10.5-15 LPA",
"role":"network developer",
"experience":"10 years",
"no_of_applications":"100",
"img":"https://companieslogo.com/img/orig/TCS.NS-7401f1bd.png?t=1631949260"

}

###
GET http://localhost:5016/allapplied