GET http://localhost:5016/

###
POST http://localhost:5016/browsejobs
Content-Type: application/json

{

"companyname":"Eidiko",
"contactnumber":"9856768734",
"email":"Eidiko@gmail.com",
"description":"Foundational endpoint security controls across all Windows, macOS and Linux endpoints. Boost your organization's security with 7 best practices to secure your workstations. Remove Local Admin Foundational endpoint security controls across all Windows, macOS and Linux endpoints Foundational endpoint security controls across all Windows, macOS and Linux endpoints.",
"state":"Ap",
"country":"India",
"salary":"2-4 LPA",
"role":"ux designer",
"experience":"2 years",
"no_of_applications":"120",
"img":"https://media.licdn.com/dms/image/C510BAQEdKL79FSPqKQ/company-logo_200_200/0/1568115431942?e=2147483647&v=beta&t=v5j9WciqSTfXLfykMOrjVEFvJqox5QAyuH7BS8wKbpM"

}
###
GET http://localhost:5016/allbrowse

###
DELETE http://localhost:5016/browsejobs/64d3adb113aa8a8b3950189f

###
GET http://localhost:5016/browsejobs/64def4ac7b42ca9fbff014f6