GET http://localhost:5016/

###
POST http://localhost:5016/browsejobs
Content-Type: application/json

{

"companyname":"daedalus",
"contactnumber":"7847848746",
"email":"daedalus123@gmail.com",
"description":"Foundational endpoint security controls across all Windows, macOS and Linux endpoints. Boost your organization's security with 7 best practices to secure your workstations. Remove Local Admin Foundational endpoint security controls across all Windows, macOS and Linux endpoints",
"state":"Telagana",
"country":"India",
"salary":"15-20 LPA",
"role":"tester",
"experience":"3 years",
"no_of_applications":"80"

}
###
GET http://localhost:5016/allbrowse

###
DELETE http://localhost:5016/browsejobs/64d3adb113aa8a8b3950189f

###
GET http://localhost:5016/browsejobs/64def4ac7b42ca9fbff014f6