GET http://localhost:5016/
###
POST http://localhost:5016/signup/
Content-Type: application/json

{
   "type":"applicant", 
"fullname":"mohan",
"email":"mohan34512134@gmail.com",
"mobilenumber":9867575667,
"password":"321",
"confirmpassword":"321" 

}
###
POST http://localhost:5016/login/
Content-Type: application/json

{ 
"email":"mohan34512134@gmail.com",
"password":"32156"

}

###
GET http://localhost:5016/allusers

###
GET http://localhost:5016/user/64b6776f7014c05c8e21c7a1
###

PUT http://localhost:5016/user/64b6608c69ddad95f0a4c2af
Content-Type: application/json

{
  "fullname":"alluarjun",
"mobilenumber":7689543366,
"gender":"female" 
}
###

DELETE http://localhost:5016/user/64b66155da01105e7707c8bd
