GET http://localhost:5016/

###
POST http://localhost:5016/jobs
Content-Type: application/json

{

"location":"Hyderabad",
"companyname":"pab solutions",
"description":"On the insert tab the galleries incluse items that are designed to coordinate with the overall look of your document On the insert tab the galleries incluse items that are designed to coordinate with the overall look of your document On the insert tab the galleries incluse items that are designed to coordinate with the overall look of your document On the insert tab the galleries incluse items that are designed to coordinate with the overall look of your document On the insert tab the galleries incluse items that are designed to coordinate with the overall look of your document On the insert tab the galleries incluse items that are designed to coordinate with the overall look of your document",
"state":"Telangana",
"country":"India",
"experience":"5 years",
"salary":"15 LPA"

}

###
GET http://localhost:5016/allusers

