GET http://localhost:5016/allprosm

###
POST http://localhost:5016/profile
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk


{
"profieeditor":"killar",
"rastram":"Andrapradesh",
"presentstay":"visakhapatnam",
"call":"9878987698",
"box":"killar123@gmail.com" 

}

###
POST http://localhost:5016/resumeheding1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk


{
    "resumeheading": "jkiust"
}

###
POST http://localhost:5016/profileSummary
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
    "profileSummary": "not"
}

###
POST http://localhost:5016/keySkills
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
    "KeySkills": " Boots"
}


###
POST http://localhost:5016/EmploymentDetails
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
    "TotalExperience":"5-years",
    "CurrentCTC":"1 L",
    "YourDesignation":"TEASTING",
    "YourOrganizationCategory":"corporations",
    "Type":"yes",
    "StartedWorkingFrom":"21-01-2002",
    "WorkedTill":"08-09-2020",
    "Describe":"Corporation: What It Is and How to Form One - Investopedia"
}

###
POST http://localhost:5016/EducationDetails
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
    "Degree":"B-Tech",
    "University":"JNTUK",
    "Year":"2021"
}

###
POST http://localhost:5016/ProjectDetails
Content-Type: application/json
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
    "ProjectTitle":"light Energy",
    "Description":"light energy is any type of energy generated by the sun. Solar energy is created by nuclear fusion that takes place in the sun. Fusion occurs when protons of hydrogen atoms violently collide in the sun's core and fuse to create a helium atom.",
    "GitHubLink":"https://github.com/topics/light-energy"
}

###
POST http://localhost:5016/workSample
Content-Type: application/json
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
    "WorkSample": "A work sample is a product"
}

###
POST http://localhost:5016/ResearchDetails
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
     "ResearchTitle":"Light Energy",
     "Authors":"Cleaves, Margaret Abigail",
     "PublicationDate":"2021"
}

###
POST http://localhost:5016/PresentationDetails
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
     "PresentationTittle":"polution",
     "Speaker":"Smith",
     "PresentationDate":"12/21/2020"
}

###
POST http://localhost:5016/PatentDetails
Content-Type: application/json
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk


{
     "Patent":"Brezil"
     
}
###
POST http://localhost:5016/CertificationDetails
Content-Type: application/json
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
     "CertificationName":"activities",
     "Organization":"Tcs Solutions",
     "Date":"30-04-2017"
     
}


###
POST http://localhost:5016/careerProfile
Content-Type: application/json
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
     "DesireIndustry":"Infosis solutions",
     "Preferedlocation":"Hyderabad",
     "designation1":" developer",
     "Expectedctcsalary":"3,00,000 - 6,00,000",
     "Desiredshift":"Day",
     "Employmenttype":"Full time"
     
}

###
POST http://localhost:5016/PersonalDetails
Content-Type: application/json
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
     "DateOfBirth":"06-07-1998",
     "MaritalStatus":"marriage",
     "Age":"5",
     "Languages":" english",
     "Gender":"female",
     "Address":"vizayanagaram"
     
}


###
POST http://localhost:5016/PaymentDetails
Content-Type: application/json
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRkNWQ3NGNhNmZmZDVkNWMyMjVkNmJiIiwiaWF0IjoxNjkxNzQ0NTI3LCJleHAiOjE3Mjc3NDQ1Mjd9.jkgWOgy8JfmY2upTDUaxtaEPvGLSFfCxkFMOY2TFDXk

{
     "paymentname":" kumar",
     "paymentemailid":"suneelK12@gmail.com",
     "paymentmobile":"8798798768",
     "amount":"1200"
     
}